# -*- coding: utf-8 -*-
"""pandas-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XThPD64EEl1VRoahQOpV6XxR0aboUq9a
"""

# TO CREATE THE DATA SET- PANDAS are used

import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/CardioGoodFitness-1.csv")

df.head()  #deafault rows 5

df.head(10)

df.tail(10)   #last 10 row

df.sample()   # a random row

df.sample()

df.sample()

df.sample(10)  #random 10 rows

df.shape   #rows and col count

df.dtypes   #data types

df.info()

#missing value
df.isnull().sum()

df.describe()

df.describe(include="all")    # NAN- not a number

